from snakemake.utils import min_version

min_version("6.10.0")

# Configuration file containing all user-specified settings
configfile: "config/config.yml"

report: "report/workflow.rst"

# include: "rules/.smk"
# include: "rules/.smk"
# include: "rules/.smk"
# include: "rules/.smk"
# include: "rules/.smk"
# include: "rules/.smk"
# include: "rules/.smk"


# Master rule for controlling workflow.
rule all:
	input:
		"index.html",




# Get dot rule graphs
rule dot_rulegraph:
	output:
		report("dags/rulegraph.svg", caption="report/rulegraph.rst", category="Explore rules"),
		"dags/rulegraph.png",
	shell:
		"bash workflow/scripts/rules_dag.sh"

# Get project tree
rule project_tree:
    output:
        tree="results/project_tree.txt"
    shell:
        "bash workflow/scripts/tree.sh"

# Get smk html report
rule snakemake_html_report:
	output:
		"report.html",
		"images/smkreport/screenshot.png",
	shell:
		"bash workflow/scripts/smk_html_report.sh"

rule deploy_to_github_pages:
    input:
        script="workflow/scripts/render.R",
        rmd="index.Rmd",
        rulegraph="dags/rulegraph.svg",
        tree="results/project_tree.txt",
        html2png="images/smkreport/screenshot.png",
    output:
        doc="index.html",
    shell:
        """
        R -e "library(rmarkdown); render('{input.rmd}')"
        """


