from snakemake.utils import min_version

min_version("6.10.0")

# Configuration file containing all user-specified settings
configfile: "config/config.yml"

report: "report/workflow.rst"



include: "rules/rmd_report.smk"
include: "rules/import_processed_data.smk"
# include: "rules/.smk"
# include: "rules/.smk"
# include: "rules/.smk"
# include: "rules/.smk"
# include: "rules/.smk"


# Master rule for controlling workflow.
rule all:
	input:
		"index.html",
        "data/processed_data.rda"
