from snakemake.utils import min_version

min_version("6.10.0")

# Configuration file containing all user-specified settings
configfile: "config/config.yml"

report: "report/workflow.rst"

include: "rules/qiime2_viz.smk"
include: "rules/rmd_report.smk"
# include: "rules/visual_types.smk"

rule all:
	input:
		"index.html",

        # "data/feature.qza", 
        # "data/taxonomy.qza", 
        # "data/metadata.tsv",
        # "data/shannon.qza",

        # "resources/feature_table.qza",
        # "resources/sample_metadata.tsv",
        # "resources/taxonomy.qza",
        # "resources/rooted_tree.qza",
        # "resources/shannon_vector.qza",
        
        "data/qiime2_phyloseq.rds",
        "data/qiime2_phyloseq_demo.rds",

		"figures/q2r_venndiagram.svg",
		# "figures/q2r_lineplot.svg",
		"figures/q2r_jitterplot.svg",
		"figures/q2r_pcoa.svg",
		"figures/q2r_heatmap.svg",
		"figures/q2r_barplot.svg",


        # expand("visual_types/heatmaps/{prefix}.Rmd", prefix=config["heatmaps"]),
        # expand("visual_types/hclusters/{prefix}.Rmd", prefix=config["hclusters"]),
        # expand("visual_types/barplots/{prefix}.Rmd", prefix=config["barplots"]),
        # expand("visual_types/boxplots/{prefix}.Rmd", prefix=config["boxplots"]),
        # expand("visual_types/ordinations/{prefix}.Rmd", prefix=config["ordinations"]),
        # expand("visual_types/phylotrees/{prefix}.Rmd", prefix=config["phylotrees"]),
