# config.yml

heatmaps:
  - correlation

hclusters:
  - hclusters

barplots:
  - vbars
  - hbars
  - circular

boxplots:
  - boxplots
  - violin
  - jitters
  - strip

ordinations:
  - pca
  - pcoa
  - nmds

distances:
  - jaccard
  - thetayc
  - bray

phylotrees:
  - phylotrees